### ISSUE TITLE
Color styles already exist, even after deleting them.

### ISSUE THREAD

**Issue by nrthbound** [kaleidocode-app/chroma#6] opened 2019-09-18 14:46 UTC
I created the blue palette from Tailwind, added them, but had to delete them for organization purposes. When trying to re-add them, I keep getting told they already exist, even though they're not in any document I'm trying to use Chroma in.

**Comment by miguelsolorio** [comment] 2019-09-20 15:38
Do you have a file example that I can take a look at?

I think this is an issue with the Figma API where items that are copied from one file to another carry over the properties of the previous styles. Here's an example:

I have color style in one file and it's applied to this rectangle, when looking at the `fillStyleId` property (it's the ID of the color style), it tells me it's `"S:953b30b53bf627e0bd83ee54f363573b1c5b8fb6,193:40"`

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/35271042/65340066-41f02780-db82-11e9-9139-8d123d438b95.png">

Now I copy this rectangle and paste it into a separate file, and you can see that there are no color styles applied when I select it but when I check the properties it's telling me that there is an ID (a new one):

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/35271042/65340168-8aa7e080-db82-11e9-9b84-9dd1331152c6.png">

So this is clearly a bug from Figma, when you copy items over those properties should be cleared.

**Comment by nrthbound** [comment] 2019-09-20 15:55
Yeah, I believe this is 100% true. I'll see if I can get that information forwarded over to them. It would work fine if I did it 1 layer at a time instead of shift-clicking a list of them though. Crazy.

**Comment by miguelsolorio** [comment] 2019-09-20 16:14
What would probably work here is to copy the hex code and paste into a new rectangle. Sorry for the trouble, I'll see if there is a way to clear this from the plugin but last I checked there wasn't.

**Comment by nrthbound** [comment] 2019-09-23 15:11
Figma Support is quite useless. They're not understanding that the issue is on their end. Will update here when I know more. Thanks.

**Comment by miguelsolorio** [comment] 2019-09-23 17:07
I had a conversation with an engineer at Figma a while ago because this keeps coming, posting here in case anyone comes across this:

> I took a look at this some more. When you copy paste a node linked to a local style in one file and paste it into another, the node gets pasted as a node linked to a remote style.
> 
> The UI doesn’t show that node as having a style at all, because the remote style doesn’t actually reference anything that exists in the team library. However, if you were to later publish the original local style, you would find that the pasted node automatically change to being linked to that style.
>
> So the fillStyleId (along with the style object itself) does get copied over to the new file to support this kind of behavior. I don’t have a strong opinion of whether that should mean the API should expose fillStyleId in that case.

I've mentioned that this feels like a bug to me because it is unexpected behavior and there is no way to say "Don't copy the old style".

**Comment by miguelsolorio** [comment] 2019-10-23 05:20
One workaround I've found is to add a new fill color then immediately remove that fill color, this clears the old color style.

Will close this issue since it's a Figma bug.

**Closed as completed by miguelsolorio** 2019-10-23 05:20 UTC
